server:
  port: 9002

spring:
  application:
    name: USER-SERVICE
  zipkin:
    base-url: http://127.0.0.1:9411/


management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

resilience4j.circuitbreaker:
  instances:
    userService:
      registerHealthIndicator: true
      ringBufferSizeInClosedState: 5
      ringBufferSizeInHalfOpenState: 3
      waitDurationInOpenState: 10s
      failureRateThreshold: 50
#      eventConsumerBufferSize: 10
#        failureRateThreshold: 50
#        minimumNumberOfCalls: 5
#        permittedNumberOfCallsInHalfOpenState: 3
#        slidingWindowSize: 10
#        waitDurationInOpenState: 5s
#        slidingWindowType: COUNT_BASED

resilience4j.ratelimiter:
  instances:
    userService:
      limitForPeriod: 10
      limitRefreshPeriod: 100000
      timeoutDuration: 1000ms
      
      
resilience4j.retry:
  instances:
    userService:
      maxRetryAttempts: 5
      waitDuration: 10000
      
 #Bulkhead either is not working or doesn't show in prometheus
resilience4j.bulkhead:    
  instances:
    userService:
      maxWaitDuration: 10ms
      maxConcurrentCall: 20

resilience4j.thread-pool-bulkhead:
  instances:
    userService:
      maxThreadPoolSize: 1
      coreThreadPoolSize: 1
      queueCapacity: 1
